spring:
  profiles:
    active: test12

---

server:
  port: 8201

spring:
  profiles: dev12
  application:
    name: test-cloud-dev-2.0

---

spring:
  profiles: test12
  application:
    name: test-cloud-test-2.0
